name: SonarQube Analysis (Self-Hosted)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarQubeScan:
    name: SonarQube Scan and Quality Gate Check
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install

      # GitHub Action to run SonarQube scan
      - name: Run SonarQube Scan
        run: | 
          sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # GitHub Action to check Quality Gate status after scan
      - name: Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

